### ISSUE TITLE
Generated Bukkit plugin.yml use `soft-depend` instead of `softdepend`

### ISSUE THREAD

**Issue by nostalfinals** [jpenilla/resource-factory#21]
My configuration:

```kotlin
bukkitPluginYaml {
    depend.add("provider")
    depend.add("member")
    depend.add("interactive")
    softDepend.add("Vault")
    softDepend.add("HuskHomes")
}
```

Generated file:

```yaml
api-version: '1.20'
name: essentials
version: 1.1.0
main: ink.pmc.essentials.PaperPlugin
depend:
- provider
- member
- interactive
- dependency-loader
- utils
soft-depend:
- Vault
- HuskHomes
```

But it should be `softdepend`:

![image](https://github.com/user-attachments/assets/49e6a122-3c46-407d-a888-44a8d2bccc6b)
